require 'spec_helper'

describe 'Complex Usage' do

  # testing the sanitizing of file names as well as spacing of
  # config file values with varying lengths
  describe file('/etc/security/limits.d/_sanitized_name_.conf') do
    it { is_expected.to be_file }
    it { is_expected.to be_mode(644) }
    it { is_expected.to be_owned_by('root') }
    it { is_expected.to be_grouped_into('root') }
    its(:content) do
      is_expected.to eq(<<-EOF
# Generated by Chef for node limits-test-node
# Local modifications will be overwritten!

a     hard nofile   50000
b     -    nice     5000
user1 soft priority 500

# End of file
      EOF
      )
    end
  end

  describe file('/etc/security/limits.d/valid_and_invalid.conf') do
    it { is_expected.to be_file }
    it { is_expected.to be_mode(644) }
    it { is_expected.to be_owned_by('root') }
    it { is_expected.to be_grouped_into('root') }
    its(:content) do
      is_expected.to eq(<<-EOF
# Generated by Chef for node limits-test-node
# Local modifications will be overwritten!

a hard nofile   123
b -    nice     456

# The following limits were detected as invalid by Chef
# c hard    niceeee 123
# d softish nproc   456

# End of file
      EOF
      )
    end
  end

  describe file('/etc/security/limits.d/only_invalid.conf') do
    it { is_expected.to be_file }
    it { is_expected.to be_mode(644) }
    it { is_expected.to be_owned_by('root') }
    it { is_expected.to be_grouped_into('root') }
    its(:content) do
      is_expected.to eq(<<-EOF
# Generated by Chef for node limits-test-node
# Local modifications will be overwritten!

# The following limits were detected as invalid by Chef
# phil squishy maxlogins 5
# kyle softish nproc   678

# End of file
      EOF
      )
    end
  end

end
