require 'spec_helper'

describe 'Simple Usage' do

  describe file('/etc/security/limits.conf') do
    it { is_expected.to be_file }
    it { is_expected.to be_mode(644) }
    it { is_expected.to be_owned_by('root') }
    it { is_expected.to be_grouped_into('root') }
    its(:content) do
      is_expected.to eq(<<-EOF
# Generated by Chef for node limits-test-node
# Local modifications will be overwritten!

* hard nofile 12345
* soft nofile 5678

# End of file
      EOF
      )
    end
  end

  describe file('/etc/security/limits.d/alice.conf') do
    it { is_expected.to be_file }
    it { is_expected.to be_mode(644) }
    it { is_expected.to be_owned_by('root') }
    it { is_expected.to be_grouped_into('root') }
    its(:content) do
      is_expected.to eq(<<-EOF
# Generated by Chef for node limits-test-node
# Local modifications will be overwritten!

alice hard nofile 500
alice soft nofile 250

# End of file
      EOF
      )
    end
  end

end
